---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: pythonsample
spec:
  image: gcr.io/triggermesh/pythonsample
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: default
