---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: bashtoy
spec:
  image: gcr.io/triggermesh/bash-ce
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: default
